Ho: Network latency has NOT gone up since we switched internet service providers

Ha: Network latency has gone up since we switched internet service providers

True Positive: Latency really did not go up
True Negative: Latency really did go up
False Positive:(Type 1) Latency did go up and I said it did
False Negative:(Type 2) Latency did not go up I said it did

Ho: The website redesign has not fallen below the customer approval rating threshold of 95%

Ho: The website redesign has fallen below the customer approval rating threshold of 95%

True Positive:  Approval rating did not fall below 95%
True Negative:  Approval rating did fall below 95%
False Positive:(Type 1) Approval rating fell below 95% and I said it had not
False Negative:(Type 2) Approval rating did not fall below 95% and I said it had 

Ho: Sales of the new Macbook improved by 20,000 units in the month folllowing the new commercial.

Ha: Sales of the new Macbook did not improve by 20,000 units in the month folllowing the new commercial.

True Positive:  Sales improved by 20,000 units
True Negative:  Sales did not improve by 20,000 units
False Positive:(Type 1) Sales did not improve by 20,000 units and I said they did 
False Negative:(Type 2) Sales improved by 20,000 units and I said they did not

In [4]:
#standard data imports
import pandas as pd
import numpy as np

#pulling sample dataset
from pydataset import data

#new library!! for stats!!! 
from scipy import stats

In [87]:
alpha = 0.05

Ho: Using a macbook is not dependent on being a codeup student

Ha: Using a macbook is dependent on being a codeup student

Conclusion: My p-value is less than alpha, therefore, we reject the null hypothesis

In [63]:
data = {
    'Codeup_Student': [49, 1],
    'Not_Student': [20, 30]
}

In [138]:
codeup = pd.DataFrame(data, index=['Macbook', "No_Macbook"])


In [139]:
codeup

Codeup_Student  Not_Student
Macbook                 49           20
No_Macbook               1           30

In [140]:
chi2, p, degf, expected = stats.chi2_contingency(codeup)

In [141]:
expected

array([[34.5, 34.5],
       [15.5, 15.5]])

In [142]:
codeup.values

array([[49, 20],
       [ 1, 30]])

Ho: Car class does not affect the number of cylinders
Ha: Car class does affect the number of cylinders

Conculusion: My p-value is less than alpha, therefore, we reject the null hypothesis

In [5]:
mpg = data('mpg')

In [114]:
mpg.rename(columns={'class': 'class1'}, inplace=True)

In [144]:
cars = pd.crosstab(mpg.cyl, mpg.class1)
cars

class1  2seater  compact  midsize  minivan  pickup  subcompact  suv
cyl                                                                
4             0       32       16        1       3          21    8
5             0        2        0        0       0           2    0
6             0       13       23       10      10           7   16
8             5        0        2        0      20           5   38

In [154]:
chi2, car_p, dof, expected = stats.chi2_contingency(cars)

In [155]:
cars.values

array([[ 0, 32, 16,  1,  3, 21,  8],
       [ 0,  2,  0,  0,  0,  2,  0],
       [ 0, 13, 23, 10, 10,  7, 16],
       [ 5,  0,  2,  0, 20,  5, 38]])

In [156]:
car_p

1.5351076620141522e-20

Ho: There is no relationship between gender and whether or not an employees works in sales or marketing

Ha: There is relationship between gender and whether or not an employees works in sales or marketing

p value is greater so fail to reject the null hypothesis, no relationship

In [169]:
import env
query = '''
select *
from employees as e
    join dept_emp as de
        using (emp_no)
    join departments as d
        using (dept_no)
    where to_date > now()
and dept_name in ('sales','marketing')
'''
url = f'mysql+pymysql://{env.username}:{env.password}@{env.host}/employees'  
relate = pd.read_sql(query, url)

In [171]:
relate.head()

dept_no  emp_no  birth_date first_name  last_name gender   hire_date  \
0    d001   10017  1958-07-06  Cristinel  Bouloucos      F  1993-08-03   
1    d001   10058  1954-10-01    Berhard   McFarlin      M  1987-04-13   
2    d001   10140  1957-03-11      Yucel      Auria      F  1991-03-14   
3    d001   10228  1953-04-21   Karoline   Cesareni      F  1991-08-26   
4    d001   10239  1955-03-31   Nikolaos      Llado      F  1995-05-08   

    from_date     to_date  dept_name  
0  1993-08-03  9999-01-01  Marketing  
1  1988-04-25  9999-01-01  Marketing  
2  1991-03-14  9999-01-01  Marketing  
3  1993-01-28  9999-01-01  Marketing  
4  1996-05-04  9999-01-01  Marketing

In [172]:
mammal = pd.crosstab(relate.gender, relate.dept_name)

In [173]:
mammal

dept_name  Marketing  Sales
gender                     
F               5864  14999
M               8978  22702

In [174]:
chi2, p, dof, expected = stats.chi2_contingency(mammal)

In [175]:
p

0.5691938610810126

In [176]:
query2 = '''select *
from dept_manager
    right join employees
        using (emp_no)''' 

managers = pd.read_sql(query2, url)

In [178]:
managers.head()

emp_no  birth_date first_name last_name gender   hire_date dept_no  \
0   10001  1953-09-02     Georgi   Facello      M  1986-06-26    None   
1   10002  1964-06-02    Bezalel    Simmel      F  1985-11-21    None   
2   10003  1959-12-03      Parto   Bamford      M  1986-08-28    None   
3   10004  1954-05-01  Chirstian   Koblick      M  1986-12-01    None   
4   10005  1955-01-21    Kyoichi  Maliniak      M  1989-09-12    None   

  from_date to_date  
0      None    None  
1      None    None  
2      None    None  
3      None    None  
4      None    None

In [180]:
managers['is_manager'] = managers.to_date.notnull()

In [181]:
managers.is_manager.value_counts()

is_manager
False    300000
True         24
Name: count, dtype: int64

In [183]:
gender = pd.crosstab(managers.is_manager, managers.gender)

In [184]:
gender

gender           F       M
is_manager                
False       120038  179962
True            13      11

In [186]:
p

#My p-value is greater than alpha, fail to reject the null hypothesis.
# We can conclude this is no relationship between gender and being a manager.

0.5691938610810126