In [23]:
import numpy as np
import pandas as pd
np.random.seed(123)

In [24]:
trials = nrows = 100000
dice_roll = ncols = 2
rolls = np.random.choice([1, 2, 3, 4, 5, 6], trials * dice_roll).reshape(nrows, ncols)

In [25]:
rolls

array([[6, 3],
       [5, 3],
       [2, 4],
       ...,
       [5, 5],
       [5, 4],
       [4, 6]])

In [26]:
rolls =pd.DataFrame(rolls)

In [27]:
rolls.columns = ["roll_one","roll_two"]

In [28]:
rolls

roll_one  roll_two
0             6         3
1             5         3
2             2         4
3             3         4
4             2         2
...         ...       ...
99995         3         4
99996         3         2
99997         5         5
99998         5         4
99999         4         6

[100000 rows x 2 columns]

In [29]:
(rolls.roll_one == rolls.roll_two) == True

0        False
1        False
2        False
3        False
4         True
         ...  
99995    False
99996    False
99997     True
99998    False
99999    False
Length: 100000, dtype: bool

In [30]:
rolls["doubles"] = (rolls.roll_one == rolls.roll_two) == True

In [9]:
rolls

roll_one  roll_two  doubles
0              3         2    False
1              3         6    False
2              2         1    False
3              1         5    False
4              3         2    False
...          ...       ...      ...
999995         2         2     True
999996         2         3    False
999997         4         2    False
999998         4         2    False
999999         3         3     True

[1000000 rows x 3 columns]

In [31]:
rolls["doubles"].value_counts()

doubles
False    83503
True     16497
Name: count, dtype: int64

In [32]:
round((16497/100000) * 100,2) #16.65 % odds of rolling doubles

16.5

In [33]:
coin_flips = ncols = 8
HEADS = 1
TAILS = 0
trials = nrows = 100000
heads_or_tails = np.random.choice([HEADS,TAILS], trials * coin_flips).reshape(nrows, ncols)

In [34]:
heads_or_tails

array([[0, 0, 0, ..., 0, 0, 1],
       [1, 1, 1, ..., 1, 0, 1],
       [1, 1, 0, ..., 0, 1, 1],
       ...,
       [1, 0, 1, ..., 1, 1, 1],
       [1, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 1, 1, 1]])

In [35]:
determine_odds = pd.DataFrame(heads_or_tails)

In [36]:
determine_odds

0  1  2  3  4  5  6  7
0      0  0  0  0  1  0  0  1
1      1  1  1  1  0  1  0  1
2      1  1  0  0  0  0  1  1
3      1  0  0  0  1  0  1  1
4      0  0  1  0  1  1  0  1
...   .. .. .. .. .. .. .. ..
99995  1  0  1  1  0  1  0  1
99996  1  1  1  0  0  0  1  1
99997  1  0  1  0  1  1  1  1
99998  1  0  0  1  1  0  1  0
99999  1  0  0  1  1  1  1  1

[100000 rows x 8 columns]

In [37]:
was_heads = (determine_odds == 1).sum(axis=1)

In [38]:
was_heads_3 = ((determine_odds == 1).sum(axis=1) == 3)

In [39]:
was_heads_more_than_3 = ((determine_odds == 1).sum(axis=1) > 3)

In [40]:
determine_odds["three_heads"] = was_heads_3

In [41]:
determine_odds["is_three_heads_or_more"] = was_heads_more_than_3

In [42]:
determine_odds

0  1  2  3  4  5  6  7  three_heads  is_three_heads_or_more
0      0  0  0  0  1  0  0  1        False                   False
1      1  1  1  1  0  1  0  1        False                    True
2      1  1  0  0  0  0  1  1        False                    True
3      1  0  0  0  1  0  1  1        False                    True
4      0  0  1  0  1  1  0  1        False                    True
...   .. .. .. .. .. .. .. ..          ...                     ...
99995  1  0  1  1  0  1  0  1        False                    True
99996  1  1  1  0  0  0  1  1        False                    True
99997  1  0  1  0  1  1  1  1        False                    True
99998  1  0  0  1  1  0  1  0        False                    True
99999  1  0  0  1  1  1  1  1        False                    True

[100000 rows x 10 columns]

In [43]:
determine_odds["three_heads"].value_counts()

three_heads
False    77872
True     22128
Name: count, dtype: int64

In [2]:
round((219013/1000000)*100,2) #21% chance of three heads

21.9

In [44]:
determine_odds["is_three_heads_or_more"].value_counts()

is_three_heads_or_more
True     63372
False    36628
Name: count, dtype: int64

In [25]:
round((363071/1000000)*100,2) #63% chance of more than three heads

36.31

In [45]:
cohorts = ncols = 2
trials = nrows = 1000000
webdev_cohort_1 =1
webdev_cohort_2 = 2
webdev_cohort_3 = 3
data_science_cohort = 4

billboards = np.random.choice([webdev_cohort_1,webdev_cohort_2,webdev_cohort_3,data_science_cohort], trials * cohorts).reshape(nrows, ncols)

In [46]:
billboards

array([[4, 2],
       [3, 3],
       [1, 2],
       ...,
       [2, 4],
       [2, 1],
       [4, 3]])

In [47]:
ds_billboard = pd.DataFrame(billboards)

In [48]:
ds_billboard

0  1
0       4  2
1       3  3
2       1  2
3       4  1
4       3  1
...    .. ..
999995  4  4
999996  3  3
999997  2  4
999998  2  1
999999  4  3

[1000000 rows x 2 columns]

In [49]:
(ds_billboard == 4).sum(axis=1) >= 2

0         False
1         False
2         False
3         False
4         False
          ...  
999995     True
999996    False
999997    False
999998    False
999999    False
Length: 1000000, dtype: bool

In [50]:
ds_billboard["two_data_science"] = (ds_billboard == 4).sum(axis=1) >= 2

In [51]:
ds_billboard

0  1  two_data_science
0       4  2             False
1       3  3             False
2       1  2             False
3       4  1             False
4       3  1             False
...    .. ..               ...
999995  4  4              True
999996  3  3             False
999997  2  4             False
999998  2  1             False
999999  4  3             False

[1000000 rows x 3 columns]

In [52]:
ds_billboard["two_data_science"].value_counts() #6.7 % chance of two data science billboards

two_data_science
False    937210
True      62790
Name: count, dtype: int64

In [53]:

pop_tart =3
dev = 1.5
days= 5
trials=100000

In [54]:
daily_tarts = np.random.normal(pop_tart,dev,(trials,days)) #FIX TARTS

In [56]:
weekly_poptarts = daily_tarts.sum(axis=1)

In [57]:
weekly_poptarts

array([14.57716943, 12.69433107, 15.49202468, ..., 18.80449573,
       15.22430975, 17.11720525])

In [89]:
((17 - weekly_poptarts)>=1).mean()

0.61477

In [59]:
men = 178
st_men = 8
women = 170
st_women = 6
trials =100000

In [63]:
men_heights =  np.random.normal(men,st_men,trials)
women_heights =  np.random.normal(women,st_women,trials)

In [64]:
(women_heights > men_heights).mean()

0.21084

In [90]:
outcomes = ["pass","fail"] #FIX
maybees =[249/250,1/250]
students = 50
trails =100000

In [102]:
install = np.random.choice(outcomes,(trials,students),p=maybees)
install
total_fails = (install== "fail").sum(axis=1)

In [103]:
total_fails

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [104]:
(total_fails == 0).mean()

0.8

In [107]:
#update to 100 students
students = 100

install = np.random.choice(outcomes, (trials, students),
                p=maybees)
total_fails = (install == 'fail').sum(axis=1)

(total_fails == 0).mean()

0.72

In [108]:
#update to 150 students
students = 150

install = np.random.choice(outcomes, (trials, students),
                p=maybees)
total_fails = (install == 'fail').sum(axis=1)

(total_fails == 0).mean()

0.54

In [109]:
#update to 450 students
students = 450

install = np.random.choice(outcomes, (trials, students),
                p=maybees)
total_fails = (install == 'fail').sum(axis=1)

(total_fails == 0).mean()

0.22

In [100]:
people = ncols = 23
trials = nrows= 100
same_birth = np.random.choice(birthday, trials * people).reshape(nrows, ncols)

In [14]:
birthday = range(1,366)
same_birth2 = np.random.choice(birthday)

In [17]:
same_birth

array([[ 74, 223, 352, ...,  89, 150, 299],
       [ 81, 115, 234, ..., 208, 214,   4],
       [186,  45,  34, ...,   1, 200, 161],
       ...,
       [163, 339,  61, ..., 186, 333,  91],
       [102, 290, 288, ..., 314, 108,  95],
       [124, 121, 148, ..., 320, 209, 248]])

In [75]:
p_truck = 0.7 #FIX
days = 3
trials = 100000

In [78]:
 is_there_truck = np.random.random((trials,days))

In [79]:
yes_truck =  is_there_truck < p_truck

In [80]:
yes_truck

array([[ True,  True, False],
       [ True, False,  True],
       [ True,  True,  True],
       ...,
       [ True,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [110]:
(yes_truck.sum(axis=1)==0).mean()

0.02702

In [113]:
modays=5

In [116]:
is_there_truck_ = np.random.random((trials, modays))

yes_truck = is_there_truck < p_truck

#update to show at least one truck shows up this week
(yes_truck.sum(axis=1) >= 1).mean()

0.97298

In [81]:
people = 23
birthday = list(range(1,366))
trials = 100000

In [82]:
samesies = np.random.choice(birthday,(trials,people))

In [83]:
samesies = pd.DataFrame(samesies)

In [84]:
samesies

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0       19  175  142  142  269   71  118  121  205  182  ...   52  172   78   
1      180   60  241  291  202  294  329  188  319  324  ...  143   51  315   
2      295   25   68  150   29  219   86  335  181  237  ...  156  160  298   
3      146   46  201  289  261   63  323  151  357   15  ...  183  359  281   
4      124  141   10  243  278  118  142  320    6  202  ...  200   96   87   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  180   78  355  161  205  170  348  320  116  273  ...  244  216   33   
99996  266  302  108  172    9   73   72   56  294  359  ...  181  338  159   
99997  329  243  252  221   50  102  205  248  223   83  ...  228   56  295   
99998  241   79    7   95   71   26   94  282   66  102  ...   55  106   55   
99999  220    9  268  341  353  271  227  314  354   27  ...  339  354  149   

        16   17   18   19   20   21   22  
0      184   18  280  116  195   50  283  
1      181  277  179  124  135  331   50  
2      352   78   62  207  134   39  344  
3      355  294  291  304   45  143   26  
4      147  328  300   50  344  278  254  
...    ...  ...  ...  ...  ...  ...  ...  
99995   29  279   66   26  108  301  315  
99996   77  340  262  149   80  197  190  
99997  323   32  106   59  226  277  171  
99998  309  273  318  279  148  218   61  
99999  183   84  208    7  172  111  314  

[100000 rows x 23 columns]

In [86]:
samesies.nunique(axis=1)

0        22
1        23
2        23
3        23
4        22
         ..
99995    22
99996    23
99997    23
99998    22
99999    21
Length: 100000, dtype: int64

In [87]:
  samesies.nunique(axis=1) < people

0         True
1        False
2        False
3        False
4         True
         ...  
99995     True
99996    False
99997    False
99998     True
99999     True
Length: 100000, dtype: bool

In [88]:
  (samesies.nunique(axis=1) < people).mean()

0.50959

In [111]:
#20 people
people = 20

birthdays = np.random.choice(birthday, (trials, people))
samesies = pd.DataFrame(birthdays)

(samesies.nunique(axis=1) < people).mean()

0.48

In [112]:
#40 people
people = 40

birthdays = np.random.choice(birthday, (trials, people))
samesies = pd.DataFrame(birthdays)

(samesies.nunique(axis=1) < people).mean()

0.89